/**
 * Invoicing Domain Types & Status Governance
 * Phase 14 — DealFlow360
 */

// Invoice Status Enum
export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  VOID: 'VOID',
  CANCELLED: 'CANCELLED',
};

// Allowed Status Transition Governance Map
export const INVOICE_TRANSITIONS = {
  [INVOICE_STATUS.DRAFT]: [INVOICE_STATUS.ISSUED, INVOICE_STATUS.CANCELLED],
  [INVOICE_STATUS.ISSUED]: [
    INVOICE_STATUS.PARTIALLY_PAID,
    INVOICE_STATUS.PAID,
    INVOICE_STATUS.OVERDUE,
    INVOICE_STATUS.VOID,
    INVOICE_STATUS.CANCELLED,
  ],
  [INVOICE_STATUS.PARTIALLY_PAID]: [INVOICE_STATUS.PAID, INVOICE_STATUS.OVERDUE, INVOICE_STATUS.VOID],
  [INVOICE_STATUS.OVERDUE]: [INVOICE_STATUS.PARTIALLY_PAID, INVOICE_STATUS.PAID, INVOICE_STATUS.VOID],
  [INVOICE_STATUS.PAID]: [],
  [INVOICE_STATUS.VOID]: [],
  [INVOICE_STATUS.CANCELLED]: [],
};
