/**
 * Fulfillment, Packing, Shipping & Delivery Domain Types & Status Enums
 * Phase 13 — DealFlow360
 */

// Fulfillment Status Enum
export const FULFILLMENT_STATUS = {
  PENDING: 'PENDING',
  READY: 'READY',
  PICKING: 'PICKING',
  PICKED: 'PICKED',
  PACKING: 'PACKING',
  PACKED: 'PACKED',
  SHIPMENT_CREATED: 'SHIPMENT_CREATED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

// Pick List Status Enum
export const PICK_LIST_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

// Package Status Enum
export const PACKAGE_STATUS = {
  OPEN: 'OPEN',
  PACKED: 'PACKED',
  CANCELLED: 'CANCELLED',
};

// Shipment Status Enum
export const SHIPMENT_STATUS = {
  SHIPMENT_CREATED: 'SHIPMENT_CREATED',
  SHIPPED: 'SHIPPED',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RETURNED: 'RETURNED',
  CANCELLED: 'CANCELLED',
};

// Carrier Status Enum
export const CARRIER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

// Fulfillment Priority Enum
export const FULFILLMENT_PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

/**
 * Valid Status Transition Maps (Governance)
 */
export const FULFILLMENT_TRANSITIONS = {
  [FULFILLMENT_STATUS.PENDING]: [FULFILLMENT_STATUS.READY, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.READY]: [FULFILLMENT_STATUS.PICKING, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.PICKING]: [FULFILLMENT_STATUS.PICKED, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.PICKED]: [FULFILLMENT_STATUS.PACKING, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.PACKING]: [FULFILLMENT_STATUS.PACKED, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.PACKED]: [FULFILLMENT_STATUS.SHIPMENT_CREATED, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.SHIPMENT_CREATED]: [FULFILLMENT_STATUS.COMPLETED, FULFILLMENT_STATUS.CANCELLED],
  [FULFILLMENT_STATUS.COMPLETED]: [],
  [FULFILLMENT_STATUS.CANCELLED]: [],
};

export const SHIPMENT_TRANSITIONS = {
  [SHIPMENT_STATUS.SHIPMENT_CREATED]: [SHIPMENT_STATUS.SHIPPED, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.SHIPPED]: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.IN_TRANSIT]: [SHIPMENT_STATUS.OUT_FOR_DELIVERY, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.OUT_FOR_DELIVERY]: [SHIPMENT_STATUS.DELIVERED, SHIPMENT_STATUS.DELIVERY_FAILED],
  [SHIPMENT_STATUS.DELIVERY_FAILED]: [SHIPMENT_STATUS.RETURNED, SHIPMENT_STATUS.OUT_FOR_DELIVERY],
  [SHIPMENT_STATUS.DELIVERED]: [],
  [SHIPMENT_STATUS.RETURNED]: [],
  [SHIPMENT_STATUS.CANCELLED]: [],
};
