/**
 * Salesperson Workspace Types & Lifecycle Definitions
 */

export const SALESPERSON_REQUEST_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REQUIREMENT_CLARIFICATION: 'REQUIREMENT_CLARIFICATION',
  REQUIREMENT_CONFIRMED: 'REQUIREMENT_CONFIRMED',
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED',
};

export const SALESPERSON_REQUEST_STATUS_LABELS = {
  SUBMITTED: 'Submitted',
  UNDER_REVIEW: 'Under Review',
  REQUIREMENT_CLARIFICATION: 'Clarification Requested',
  REQUIREMENT_CONFIRMED: 'Requirement Confirmed',
  CANCELLED: 'Cancelled',
  CLOSED: 'Closed',
};

export const SALESPERSON_REQUEST_STATUS_VARIANTS = {
  SUBMITTED: 'info',
  UNDER_REVIEW: 'warning',
  REQUIREMENT_CLARIFICATION: 'amber',
  REQUIREMENT_CONFIRMED: 'success',
  CANCELLED: 'danger',
  CLOSED: 'neutral',
};

export const SALESPERSON_REQUEST_PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const SALESPERSON_ACTIONS = {
  CLAIM_REQUEST: 'CLAIM_REQUEST',
  START_REVIEW: 'START_REVIEW',
  ASK_CLARIFICATION: 'ASK_CLARIFICATION',
  CONFIRM_REQUIREMENT: 'CONFIRM_REQUIREMENT',
  CLOSE_REQUEST: 'CLOSE_REQUEST',
};
